name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose && cargo install cargo-tarpaulin && cargo tarpaulin --ignore-tests
    - name: lint
      run: rustup component add clippy && cargo clippy -- -D warnings
    - name: format
      run: rustup component add rustfmt && cargo fmt -- --check
    - name: audit
      run: cargo install cargo-audit && cargo audit
